### ISSUE TITLE
SEVERE: null

### ISSUE THREAD

**Issue by massimilianomartella** [angryelectron/thingspeak-java#4]
Hi!, 
I try to send a multiple msg to thingSpeak and I have some problems:

when I send only one msg, with this class I have no problem:

```java
package com.IoT.thingSpeak;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import com.angryelectron.thingspeak.Channel;
import com.angryelectron.thingspeak.Entry;
import com.angryelectron.thingspeak.ThingSpeakException;
import com.angryelectron.thingspeak.log4j.ThingSpeakAppender;
import com.mashape.unirest.http.exceptions.UnirestException;

public class ThingSpeakWebClient {
	private String apiWriteKey = "***************************";
	private int channelNumber = *******;
	private Channel channel;

	public ThingSpeakWebClient() {

		System.setProperty("org.apache.commons.logging.Log",
				"org.apache.commons.logging.impl.Jdk14Logger");
		channel = new Channel(channelNumber, apiWriteKey);
	}

	public synchronized void sendMsg1(int field1, Double value) {

		Entry entry = new Entry();
		entry.setField(field1, String.valueOf(value));
		try {
			channel.update(entry);
			System.out.println("Msg sended!");
		} catch (UnirestException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ThingSpeakException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public synchronized void sendMsg2(int field1, Double value) {
		ThingSpeakAppender appender = new ThingSpeakAppender();
		appender.configureChannel(channelNumber, apiWriteKey, "http://api.thingspeak.com");
		appender.setThreshold(Level.INFO);
		appender.activateOptions();
		appender.setData(field1, value);
		Logger.getRootLogger().addAppender(appender);
		Logger.getLogger(this.getClass()).log(Level.INFO, "Hello World");	
	}

	public static void main(String[] args) throws Exception {
		ThingSpeakWebClient ts = new ThingSpeakWebClient();
		//ts.sendMsg1(1, 28.9);
		ts.sendMsg2(1, 28.9);
	}
}

```

But, I try to send a multiple msg, for example using the Observable pattern, the second msg has this problem:

```java
Dec 28, 2015 3:28:02 PM com.angryelectron.thingspeak.log4j.ThingSpeakAppender append
SEVERE: null
com.angryelectron.thingspeak.ThingSpeakException: Update failed.
	at com.angryelectron.thingspeak.Channel.update(Channel.java:182)
	at com.angryelectron.thingspeak.log4j.ThingSpeakAppender.append(ThingSpeakAppender.java:145)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:221)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:57)
	at org.apache.log4j.Category.callAppenders(Category.java:187)
	at org.apache.log4j.Category.forcedLog(Category.java:372)
	at org.apache.log4j.Category.log(Category.java:846)
	at com.IoT.thingSpeak.ThingSpeakWebClient.sendMsg(ThingSpeakWebClient.java:49)
	at com.IoT.TemperatureHumidityMonitoring.ModelReactiveControlSensor.lambda$5(ModelReactiveControlSensor.java:108)
	at com.IoT.TemperatureHumidityMonitoring.ModelReactiveControlSensor$$Lambda$9/1811883046.call(Unknown Source)
	at rx.Observable$32.onNext(Observable.java:7466)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
	at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
	at rx.Scheduler$Worker$1.call(Scheduler.java:120)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
```

More precisely: my code has some problem with this function, in `Channel.java`:

```java
/**
	 * Update channel with new data.
	 *
	 * @param entry
	 *            The new data to be posted.
	 * @return The id of the new entry.
	 * @throws UnirestException
	 *             The request cannot be made.
	 * @throws ThingSpeakException
	 *             The request is invalid.
	 */
	public Integer update(Entry entry) throws UnirestException,
			ThingSpeakException {
		HttpResponse<String> response = Unirest.post(APIURL + "/update")
				.header(APIHEADER, this.writeAPIKey)
				.header("Connection", "close").fields(entry.getUpdateMap())
				.asString();
		if (response.getCode() != 200) {
			throw new ThingSpeakException("Request failed with code "
					+ response.getCode());
		} else if (response.getBody().equals("0")) {
			throw new ThingSpeakException("Update failed.");
		}
		return Integer.parseInt(response.getBody());
	}

``` 

The program crashes on `throw new ThingSpeakException("Update failed.");`

I need help :-)
Do you have any idea for solve this problem?!

Thank you!
Massimiliano

**Comment by abythell** [comment]
How fast are you sending channel updates?  The public Thingspeak server has a throttle which limits requests to one every 15 seconds.

What does the `response` object contain, just before the "Update Failed" exception is thrown in the `update()`  method?   Perhaps the exception handling needs to be improved to return a more meaningful error message.

(Consider removing your API key from the original post, or generating a new one to keep your channel secure)

**Comment by massimilianomartella** [comment]
Yes, every 20 second! 

```java
connectObsTemperature.interval(20, TimeUnit.SECONDS, Schedulers.io())
				.subscribe(
						(Long v) -> {
							System.out.println(v);
							ts.sendMsg(1, GetRandomDouble.getNum(0, 100));
						},
						(Throwable t) -> {
							System.out.println("error  " + t);
						},
						() -> {
							// When finish, write "Completed" on the JPanelArea
							view.setUpdatedJPaneAreaTemperature("Completed\n",
									Color.gray);
						});
```

Maybe I need to "close" the connection?! But I don't know...
With RxJava I send one msg every 20seconds, the first one is ok, but from the second one I have the above error :-(

**Comment by abythell** [comment]
Any further clues in the response object?

**Comment by massimilianomartella** [comment]
Hi!
I've solved my problem! 
The problem was that I did send two message, one for temperature and another one for humidity with two separate Thread.

When I did debug, my program worked fine, and I can send one message every 15 seconds.
Now I have modified my code to render it thread-safe :-)

Thank you for your replay!

**Comment by abythell** [comment]
Looking into a more meaningful error response...

Based on the [error code documentation](https://www.mathworks.com/help/thingspeak/error-codes.html), one might expecte an HTTP code of 429 ("too many requests"), but instead, when a channel is updated too quickly, the API responds with HTTP code 200 and "0" in the body.   

Since there is no further information that can be obtained via API(to set this error apart from others, the thingspeak-java client can't provide further details, other than throwing an exception with the message "Update failed".
